# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 351aed6d128818ae56ada5ef04e01088c418b063caf2d20ea02f4332d678a24eacf9b8fcfc102c85400fa04474665365d7002545439956dda41af1ba4e079f8b

test:
  secret_key_base: 31f178758e3660f8741889bbfbe829848189ebe54acdfb2e5d8e6a7e9f892224d47e355f367599c0f7e5889854b24073add442d87001026cfbbee3f3ccf0c32f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
