source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development do
  gem 'guard'
  gem 'guard-annotate'
  gem 'guard-rails'
  gem 'byebug'
end

gem 'rspec-rails'
gem 'mysql2', '~> 0.3.18'
gem 'factory_girl_rails'
gem 'redis-rails'
gem 'actionpack-page_caching'
gem 'actionpack-action_caching'
gem 'faker'
gem 'rack-mini-profiler'
gem 'dalli'

gem 'jquery-rails'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
