# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a0cf5dd7b0abe52cdd76dca84f36798de89f9eecac61ba9c17811c955acfcce722e4e8512888c66f9e607dba6cc71ef4bf14f3c8210317a507ae6814f6366e4

test:
  secret_key_base: ac65d564c0c5a4988960dbc391d0826ed27bb762beeb2a2f50f0f2e79886921d1a2b65976cc43b052a39f40f59047a0558589ec0e933c7892c0c9ad0085ae40a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
